//微信弹出窗口
$('#ico_wx_1').on('mousemove',function(e){
	$('.wx_conter').show();
});
$('#ico_wx_1').on('mouseout',function(e){
	$('.wx_conter').hide();
});

//社区
$('.w_forumf1').on('mousemove',function(e){
	$('.w_forumf2').removeClass('w_forum_tag');
	$('.w_forumf3').removeClass('w_forum_tag');
	$('.w_forumf1').addClass('w_forum_tag');
	$('.w_fath_1').show();
	$('.w_fath_2').hide();
	$('.w_fath_3').hide();
});
$('.w_forumf2').on('mousemove',function(e){
	$('.w_forumf3').removeClass('w_forum_tag');
	$('.w_forumf1').removeClass('w_forum_tag');
	$('.w_forumf2').addClass('w_forum_tag');
	$('.w_fath_2').show();
	$('.w_fath_1').hide();
	$('.w_fath_3').hide();
});
$('.w_forumf3').on('mousemove',function(e){
	$('.w_forumf2').removeClass('w_forum_tag');
	$('.w_forumf1').removeClass('w_forum_tag');
	$('.w_forumf3').addClass('w_forum_tag');
	$('.w_fath_3').show();
	$('.w_fath_2').hide();
	$('.w_fath_1').hide();
});

//手机注册
if($('.w_switching').length > 0){
	$('.w_phone').on('click',function(){
		$('.w_pregister').show();
		$('.w_eregister').hide();
		$('.w_uregister').hide();
		$('.w_phone').addClass('w_hover');
		$('.w_em').removeClass('w_hover');
		$('.w_ur').removeClass('w_hover');
	});
	$('.w_em').on('click',function(){
		$('.w_pregister').hide();
		$('.w_eregister').show();
		$('.w_uregister').hide();
		$('.w_phone').removeClass('w_hover');
		$('.w_em').addClass('w_hover');
		$('.w_ur').removeClass('w_hover');
	});
	$('.w_ur').on('click',function(){
		$('.w_pregister').hide();
		$('.w_eregister').hide();
		$('.w_uregister').show();
		$('.w_phone').removeClass('w_hover');
		$('.w_em').removeClass('w_hover');
		$('.w_ur').addClass('w_hover');
	});
}